controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

lucky_number:
    path: /lucky/{max}
    controller: App\Controller\LuckyController::number
    methods: GET|HEAD